@subscription_HostAddress = http://localhost:5053

POST https://cc92-220-129-200-172.ngrok-free.app/api/Subscription/TelegramWebhook

### Send POST
POST {{subscription_HostAddress}}/api/Subscription/Subscribe
Accept: text/plain
Content-Type: application/json

{
  "userId": 13,
  "board": "Stock",
  "keyword": "標的"
}

###
### Send DELETE
DELETE {{subscription_HostAddress}}/api/Subscription/Unsubscribe
Accept: text/plain
Content-Type: application/json

{
  "userId": 12,
  "board": "Stock",
  "keyword": "標的"
}

###
